//! Tile activity tracker for the debug map.
//!
//! Records per-DSF-region tile activity (cache hits, misses, generation)
//! with origin tracking (FUSE on-demand vs prefetch). The executor daemon
//! writes to this tracker; the debug map API reads from it.

use std::collections::HashMap;
use std::sync::{Arc, RwLock};
use std::time::Instant;

use crate::geo_index::DsfRegion;

/// How a tile request was served.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TileOrigin {
    /// On-demand FUSE request from X-Plane.
    Fuse,
    /// Pre-loaded by the prefetch system.
    Prefetch,
}

/// How a tile request was resolved.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TileCacheResult {
    /// Found in memory cache (fast).
    CacheHit,
    /// Not in cache, generated from network (slow).
    Generated,
}

/// Activity counters for a single DSF region.
#[derive(Debug, Clone, Default)]
pub struct RegionActivity {
    /// Tiles served from cache (FUSE origin).
    pub fuse_cache_hits: u32,
    /// Tiles generated on-demand (FUSE origin, cache miss).
    pub fuse_generated: u32,
    /// Tiles served from cache (prefetch origin).
    pub prefetch_cache_hits: u32,
    /// Tiles generated by prefetch.
    pub prefetch_generated: u32,
    /// Last activity timestamp.
    pub last_activity: Option<Instant>,
}

impl RegionActivity {
    /// Total tiles served in this region.
    pub fn total(&self) -> u32 {
        self.fuse_cache_hits + self.fuse_generated + self.prefetch_cache_hits + self.prefetch_generated
    }

    /// Whether X-Plane had to wait for any tiles in this region.
    pub fn had_fuse_misses(&self) -> bool {
        self.fuse_generated > 0
    }
}

/// Thread-safe tile activity tracker.
///
/// The executor daemon records tile activity here; the debug map API
/// reads it to visualise which regions had cache hits vs misses.
///
/// Uses a global instance so the executor can record events without
/// changing any function signatures.
#[derive(Clone)]
pub struct TileActivityTracker {
    inner: Arc<RwLock<HashMap<DsfRegion, RegionActivity>>>,
}

/// Global instance — accessed by executor and debug map via `global()`.
static GLOBAL_TRACKER: std::sync::OnceLock<TileActivityTracker> = std::sync::OnceLock::new();

impl TileActivityTracker {
    pub fn new() -> Self {
        Self {
            inner: Arc::new(RwLock::new(HashMap::new())),
        }
    }

    /// Get the global tracker instance.
    pub fn global() -> &'static TileActivityTracker {
        GLOBAL_TRACKER.get_or_init(TileActivityTracker::new)
    }

    /// Record a tile event.
    pub fn record(
        &self,
        tile_lat: f64,
        tile_lon: f64,
        origin: TileOrigin,
        result: TileCacheResult,
    ) {
        let region = DsfRegion::new(tile_lat.floor() as i32, tile_lon.floor() as i32);

        if let Ok(mut map) = self.inner.write() {
            let activity = map.entry(region).or_default();
            match (origin, result) {
                (TileOrigin::Fuse, TileCacheResult::CacheHit) => activity.fuse_cache_hits += 1,
                (TileOrigin::Fuse, TileCacheResult::Generated) => activity.fuse_generated += 1,
                (TileOrigin::Prefetch, TileCacheResult::CacheHit) => {
                    activity.prefetch_cache_hits += 1
                }
                (TileOrigin::Prefetch, TileCacheResult::Generated) => {
                    activity.prefetch_generated += 1
                }
            }
            activity.last_activity = Some(Instant::now());
        }
    }

    /// Get a snapshot of all region activity.
    pub fn snapshot(&self) -> HashMap<DsfRegion, RegionActivity> {
        self.inner
            .read()
            .map(|map| map.clone())
            .unwrap_or_default()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_record_fuse_miss() {
        let tracker = TileActivityTracker::new();
        tracker.record(48.5, 15.3, TileOrigin::Fuse, TileCacheResult::Generated);

        let snapshot = tracker.snapshot();
        let region = DsfRegion::new(48, 15);
        let activity = snapshot.get(&region).unwrap();
        assert_eq!(activity.fuse_generated, 1);
        assert!(activity.had_fuse_misses());
    }

    #[test]
    fn test_record_prefetch_hit() {
        let tracker = TileActivityTracker::new();
        tracker.record(48.5, 15.3, TileOrigin::Prefetch, TileCacheResult::CacheHit);

        let snapshot = tracker.snapshot();
        let region = DsfRegion::new(48, 15);
        let activity = snapshot.get(&region).unwrap();
        assert_eq!(activity.prefetch_cache_hits, 1);
        assert!(!activity.had_fuse_misses());
    }

    #[test]
    fn test_multiple_events_accumulate() {
        let tracker = TileActivityTracker::new();
        tracker.record(48.5, 15.3, TileOrigin::Fuse, TileCacheResult::CacheHit);
        tracker.record(48.2, 15.8, TileOrigin::Fuse, TileCacheResult::Generated);
        tracker.record(48.9, 15.1, TileOrigin::Prefetch, TileCacheResult::Generated);

        let snapshot = tracker.snapshot();
        let region = DsfRegion::new(48, 15);
        let activity = snapshot.get(&region).unwrap();
        assert_eq!(activity.total(), 3);
        assert_eq!(activity.fuse_cache_hits, 1);
        assert_eq!(activity.fuse_generated, 1);
        assert_eq!(activity.prefetch_generated, 1);
    }

    #[test]
    fn test_negative_coordinates() {
        let tracker = TileActivityTracker::new();
        tracker.record(-34.5, 151.3, TileOrigin::Fuse, TileCacheResult::Generated);

        let snapshot = tracker.snapshot();
        let region = DsfRegion::new(-35, 151);
        let activity = snapshot.get(&region).unwrap();
        assert_eq!(activity.fuse_generated, 1);
    }
}
